version: '3.3'
services:
    consul:
        image: consul
        container_name: consul
        network_mode: bridge
        command: ["consul", "agent", "-dev", "-client", "0.0.0.0"]
        restart: always

    config-server:
        image: demo/rtn-config-server
        container_name: rtn-config-server
        network_mode: bridge
        depends_on:
            - consul
        links:
            - consul
        restart: always

    gateway-server:
        image: demo/rtn-gateway-server
        container_name: rtn-gateway-server
        network_mode: bridge
        depends_on:
            - consul
            - config-server
        links:
            - consul
            - config-server
        restart: always

    iasbp2-api:
        image: demo/iasbp2-api
        container_name: iasbp2-api
        network_mode: bridge
        depends_on:
            - consul
            - gateway-server
            - config-server
        links:
            - consul
            - gateway-server
            - config-server
        restart: always


    checlist-ui:
        image: demo/checklist-ui
        container_name: checklist-ui
        network_mode: bridge
        depends_on:
            - iasbp2-api
            - consul
            - gateway-server
            - config-server
        links:
            - iasbp2-api
        ports:
          - 4200:4200
        restart: always


